### ISSUE TITLE
Screenshot?  

### ISSUE THREAD

**Issue by PySimpleGUI** [PedroTorrado/RingsOfFire#1]
Hi there!

Your program has something most Python programs don't have....a GUI... which means you can show it to people in your readme.

![image](https://user-images.githubusercontent.com/46163555/148066437-9d855bd8-b43e-486c-891a-a176ebb6602a.png)

You can use these GitHub Issues as a way to host your images.  The image above was made by pasting the image into the issue.  GitHub did the rest and left this line of text:

`![image](https://user-images.githubusercontent.com/46163555/148066437-9d855bd8-b43e-486c-891a-a176ebb6602a.png)`

If you paste the text into a markdown document like your readme, it will embed it.

------------------------------

**import**

I initially wasn't able to run the code due to the import.   Once it was changed to

```python
import PySimpleGUI as sg

```

then it ran fine.

Congrats on the accomplishment!  💪

Keep building!

![image](https://user-images.githubusercontent.com/46163555/148066729-314c9ea6-ca17-4588-952c-fdc55b7bae25.png)

**Comment by PedroTorrado** [comment]
Hi, 
Both changes were made, thank you for your suggestions.

**Comment by PySimpleGUI** [comment]
Very nice!  You're quite welcome.  It's fun to see GUIs in repos... to see what creations are being made.  I think it helps pull in visitors to explore a little, maybe try things our or take a peek at the code.
