### ISSUE TITLE
Text cut off the screen in GUI

### ISSUE THREAD

**Issue by jt-skrivanek** [PedroTorrado/RingsOfFire#3]
Hi, in one of the text prompts the text is cut off the screen.
![image](https://user-images.githubusercontent.com/34188019/148695054-41d51349-efc7-4dbd-9326-28b8ade29d37.png)

**Comment by PedroTorrado** [comment]
Thank you for taking the time to download and check my program as well as the time to report a problem to me,
Relating to your issue, I'm not having that problem on my system, but it seems to me we are using different OS's.
Either way I already changed my code and I think I might have fixed that issue, can you check on your system and report it back to me?

**Comment by jt-skrivanek** [comment]
Thanks for the fast reply, all the text seems to be in order now.

**Comment by PedroTorrado** [comment]
Great, glad to know, if you find/found any error feel free to let me know. 
And you have anything to add to it also feel free.
