### ISSUE TITLE
Beware hardcoded Window sizes....

### ISSUE THREAD

**Issue by PySimpleGUI** [PedroTorrado/RingsOfFire#6]
I found your code was in my scratch files in PyCharm. I must have been debugging something or trying it in Jan 2022.

It's clearly an early version of your code, but I do see your code still has hard coded values for a Window's size.  The danger of doing this can be seen in this image that I see when I ran the code:

![image](https://user-images.githubusercontent.com/46163555/162327350-3fa144c1-a277-4a43-b594-cf48a9382fee.png)

As you can see, the text is cut off, and even worse, and entire button.

I recommend always allowing PySimpleGUI to determine the overall size for the window so these kinds of problems don't happen.  PySimpleGUI sizes windows to fit their contents.  If you want to make your windows a little bit bigger, then the best way to go about this is to add a little bit more size on the inside of your window. 

You can do this using the window's margins, add a few rows of blank text, put your layout into a `Column` element and adding a little bit of pad to it, and numerous other ways.

Removing the `size` resulted in a window that's not truncated.
![image](https://user-images.githubusercontent.com/46163555/162328626-77229f67-0147-4443-ad6d-2b6c60bd8800.png)

I also wanted to thank you for posting the screenshots!  ![image](https://user-images.githubusercontent.com/46163555/162328727-27b1d914-66be-495d-a185-b4016d5868da.png)

I love seeing what you're making and I'm sure your repo's visitors love seeing them too!

**Comment by PedroTorrado** [comment]
Changed all layouts and removed hardcoded values, hope this changes the behaviour of the content as intended. 
Thanks for the call, I would have never thought this could be a problem since I only saw the program through my screen and its resolution.

**Comment by PySimpleGUI** [comment]
You're quite welcome!  Glad you found it helpful and thanks for making the change.  I think it'll make for a better program for everyone as a result.
![image](https://user-images.githubusercontent.com/46163555/167624245-d5870be8-055c-4a5d-a6e8-68d430774c1c.png)
